services:
  identidock:
    build: .
    expose:
      - "9090"
    network_mode: "bridge"
    environment:
      ENV: PROD
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.0
    network_mode: "bridge"

  redis:
    image: redis:3.0
    network_mode: "bridge"